import io
import os
import gc
import time
import tempfile
import shutil
from datetime import datetime

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm, mm
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    HRFlowable, PageBreak, Image, KeepTogether,
)
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT
from reportlab.platypus import Flowable
from reportlab.pdfgen import canvas as _canvas

# ── COLOUR PALETTE ────────────────────────────────────────────────────────────
C_BG       = colors.HexColor("#FFFFFF")           # White background
C_PANEL    = colors.HexColor("#F5F5F5")          # Light gray
C_BORDER   = colors.HexColor("#E0E0E0")          # Subtle border
C_TEXT     = colors.HexColor("#1F1F1F")          # Dark text
C_MUTED    = colors.HexColor("#666666")          # Medium gray
C_BLUE     = colors.HexColor("#0056B3")          # Professional blue
C_GREEN    = colors.HexColor("#198754")          # Professional green
C_AMBER    = colors.HexColor("#FF9800")          # Professional orange
C_CORAL    = colors.HexColor("#DC3545")          # Professional red
C_TEAL     = colors.HexColor("#17A2B8")          # Professional teal
C_PURP     = colors.HexColor("#6F42C1")          # Professional purple
C_WHITE    = colors.HexColor("#FFFFFF")          # White
C_DARK     = colors.HexColor("#000000")          # Black

ACCENT_PALETTE = [C_BLUE, C_GREEN, C_AMBER, C_CORAL, C_TEAL, C_PURP]

W, H = A4   # 595.27, 841.89 pt
MARGIN = 2.0 * cm


# ─────────────────────────────────────────────────────────────────────────────
# CUSTOM CANVAS — adds header/footer on every page
# ─────────────────────────────────────────────────────────────────────────────
class ReportCanvas(_canvas.Canvas):
    def __init__(self, *args, title="", filename_short="", **kwargs):
        super().__init__(*args, **kwargs)
        self._title = title
        self._fname = filename_short
        self._saved_state_stack = []

    def showPage(self):
        self._draw_decorations()
        super().showPage()

    def save(self):
        self._draw_decorations()
        super().save()

    def _draw_decorations(self):
        page_num = self._pageNumber
        # ── top bar ───────────────────────────────────────────────────────────
        self.setFillColor(C_PANEL)
        self.rect(0, H - 30, W, 30, fill=1, stroke=0)
        self.setFillColor(C_BLUE)
        self.rect(0, H - 2, W, 2, fill=1, stroke=0)
        if page_num > 1:
            self.setFont("Helvetica-Bold", 8.5)
            self.setFillColor(C_BLUE)
            self.drawString(MARGIN, H - 16, "DATA ANALYSIS REPORT")
            self.setFont("Helvetica", 8)
            self.setFillColor(C_MUTED)
            self.drawRightString(W - MARGIN, H - 16, self._fname)

        # ── bottom bar ────────────────────────────────────────────────────────
        self.setFillColor(C_PANEL)
        self.rect(0, 0, W, 24, fill=1, stroke=0)
        self.setFillColor(C_BLUE)
        self.rect(0, 24, W, 0.5, fill=1, stroke=0)
        if page_num > 1:
            self.setFont("Helvetica", 8)
            self.setFillColor(C_MUTED)
            self.drawString(MARGIN, 8, "Generated by AutoReport · CODTECH Task 2")
            self.setFillColor(C_BLUE)
            self.drawRightString(W - MARGIN, 8, f"Page {page_num}")


# ─────────────────────────────────────────────────────────────────────────────
# STYLES
# ─────────────────────────────────────────────────────────────────────────────
def _make_styles():
    base = getSampleStyleSheet()

    def S(name, **kw):
        return ParagraphStyle(name, **kw)

    return {
        "title_cover": S("title_cover", fontSize=42, leading=50,
                          textColor=C_BLUE, fontName="Helvetica-Bold",
                          alignment=TA_LEFT, spaceAfter=12),
        "subtitle_cover": S("subtitle_cover", fontSize=14, leading=20,
                             textColor=C_TEXT, fontName="Helvetica",
                             alignment=TA_LEFT),
        "section_heading": S("section_heading", fontSize=18, leading=24,
                              textColor=C_BLUE, fontName="Helvetica-Bold",
                              spaceBefore=18, spaceAfter=12),
        "sub_heading": S("sub_heading", fontSize=12, leading=16,
                          textColor=C_DARK, fontName="Helvetica-Bold",
                          spaceBefore=12, spaceAfter=6),
        "body": S("body", fontSize=10, leading=14,
                  textColor=C_MUTED, fontName="Helvetica"),
        "body_dark": S("body_dark", fontSize=10, leading=14,
                        textColor=C_TEXT, fontName="Helvetica"),
        "caption": S("caption", fontSize=9, leading=12,
                      textColor=C_MUTED, fontName="Helvetica",
                      alignment=TA_CENTER, spaceBefore=4),
        "insight_title": S("insight_title", fontSize=10, leading=13,
                            textColor=C_BLUE, fontName="Helvetica-Bold"),
        "insight_body": S("insight_body", fontSize=9, leading=13,
                           textColor=C_TEXT, fontName="Helvetica"),
        "kv_key": S("kv_key", fontSize=9, leading=12,
                    textColor=C_MUTED, fontName="Helvetica"),
        "kv_val": S("kv_val", fontSize=10, leading=13,
                    textColor=C_TEXT, fontName="Helvetica-Bold"),
        "tag": S("tag", fontSize=9, leading=11,
                 textColor=C_WHITE, fontName="Helvetica-Bold", alignment=TA_CENTER),
    }


# ─────────────────────────────────────────────────────────────────────────────
# HELPERS
# ─────────────────────────────────────────────────────────────────────────────
def _fmt(v):
    if isinstance(v, float):
        return f"{v:,.4g}"
    if isinstance(v, int):
        return f"{v:,}"
    return str(v) if v is not None else "—"


def _hr(styles):
    return HRFlowable(width="100%", thickness=1, color=C_BORDER, spaceAfter=8, spaceBefore=4)


def _img_from_bytes(png_bytes, width=None, height=None):
    buf = io.BytesIO(png_bytes)
    img = Image(buf)
    if width:
        ratio = img.imageHeight / img.imageWidth
        img.drawWidth  = width
        img.drawHeight = width * ratio
    elif height:
        ratio = img.imageWidth / img.imageHeight
        img.drawHeight = height
        img.drawWidth  = height * ratio
    return img


def _stats_table(rows, col_widths=None):
    """Professional stats table with light theme."""
    style = TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0),  C_BLUE),
        ("BACKGROUND", (0, 1), (-1, -1), C_BG),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [C_BG, C_PANEL]),
        ("TEXTCOLOR",   (0, 0), (-1,  0),  C_WHITE),
        ("TEXTCOLOR",   (0, 1), (-1, -1),  C_TEXT),
        ("FONTNAME",    (0, 0), (-1,  0),  "Helvetica-Bold"),
        ("FONTNAME",    (0, 1), (-1, -1),  "Helvetica"),
        ("FONTSIZE",    (0, 0), (-1, -1),  9),
        ("ALIGN",       (0, 0), (-1, -1),  "CENTER"),
        ("ALIGN",       (0, 0), (0,  -1),  "LEFT"),
        ("VALIGN",      (0, 0), (-1, -1),  "MIDDLE"),
        ("TOPPADDING",  (0, 0), (-1, -1),  7),
        ("BOTTOMPADDING",(0,0), (-1, -1),  7),
        ("LEFTPADDING", (0, 0), (-1, -1),  8),
        ("RIGHTPADDING",(0, 0), (-1, -1),  8),
        ("GRID",        (0, 0), (-1, -1),  0.5, C_BORDER),
        ("LINEABOVE",   (0, 0), (-1,  0),  2, C_BLUE),
        ("LINEBELOW",   (0, 0), (-1,  0),  2, C_BLUE),
    ])
    t = Table(rows, colWidths=col_widths, repeatRows=1)
    t.setStyle(style)
    return t


# ─────────────────────────────────────────────────────────────────────────────
# PAGE BUILDERS
# ─────────────────────────────────────────────────────────────────────────────

def _cover_page(story, styles, analysis):
    fi   = analysis["file"]
    ov   = analysis.get("overview", {})
    num  = analysis.get("numeric", {})
    cat  = analysis.get("categorical", {})
    S    = styles

    # big top spacer
    story.append(Spacer(1, 3.5 * cm))

    # accent stripe — simulated with a coloured table cell
    accent_row = [["📊  DATA ANALYSIS REPORT"]]
    accent_tbl = Table(accent_row, colWidths=[W - 2*MARGIN])
    accent_tbl.setStyle(TableStyle([
        ("BACKGROUND",   (0,0), (-1,-1), C_BLUE),
        ("TEXTCOLOR",    (0,0), (-1,-1), C_WHITE),
        ("FONTNAME",     (0,0), (-1,-1), "Helvetica-Bold"),
        ("FONTSIZE",     (0,0), (-1,-1), 11),
        ("TOPPADDING",   (0,0), (-1,-1), 8),
        ("BOTTOMPADDING",(0,0), (-1,-1), 8),
        ("LEFTPADDING",  (0,0), (-1,-1), 12),
        ("GRID",         (0,0), (-1,-1), 0, colors.transparent),
    ]))
    story.append(accent_tbl)
    story.append(Spacer(1, 1.0 * cm))

    # Title = filename
    story.append(Paragraph(fi["filename"], S["title_cover"]))
    story.append(Paragraph("Automated Statistical Analysis Report", S["subtitle_cover"]))
    story.append(Spacer(1, 1.2 * cm))

    # Meta grid
    meta_rows = [
        ["File Name",    fi["filename"],    "File Type",  fi["type"].upper()],
        ["File Size",    fi["filesize"],    "Generated",  analysis["generated"]],
        ["Rows",         _fmt(ov.get("rows","—")),   "Columns", _fmt(ov.get("columns","—"))],
        ["Numeric Cols", _fmt(ov.get("numeric_cols","—")), "Categorical", _fmt(ov.get("categorical_cols","—"))],
        ["Missing Cells",f"{_fmt(ov.get('missing_cells','—'))}  ({ov.get('missing_pct',0):.1f}%)",
         "Duplicates",   _fmt(ov.get("duplicate_rows","—"))],
    ]
    meta_table_data = []
    for row in meta_rows:
        meta_table_data.append([
            Paragraph(str(row[0]), S["kv_key"]),
            Paragraph(str(row[1]), S["kv_val"]),
            Paragraph(str(row[2]), S["kv_key"]),
            Paragraph(str(row[3]), S["kv_val"]),
        ])
    cw = [(W - 2*MARGIN) / 4] * 4
    mt = Table(meta_table_data, colWidths=cw)
    mt.setStyle(TableStyle([
        ("BACKGROUND",    (0,0), (-1,-1), C_PANEL),
        ("ROWBACKGROUNDS",(0,0), (-1,-1), [C_BG, C_PANEL]),
        ("TEXTCOLOR",     (0,0), (-1, -1), C_TEXT),
        ("GRID",          (0,0), (-1,-1), 0.5, C_BORDER),
        ("TOPPADDING",    (0,0), (-1,-1), 9),
        ("BOTTOMPADDING", (0,0), (-1,-1), 9),
        ("LEFTPADDING",   (0,0), (-1,-1), 10),
        ("RIGHTPADDING",  (0,0), (-1,-1), 10),
        ("LINEABOVE",     (0,0), (-1,0),  2, C_BLUE),
        ("LINEBELOW",     (0,0), (-1,-1),  1, C_BORDER),
    ]))
    story.append(mt)
    story.append(PageBreak())


def _summary_page(story, styles, analysis):
    S   = styles
    ov  = analysis.get("overview", {})
    ins = analysis.get("insights", [])

    story.append(Paragraph("Executive Summary", S["section_heading"]))
    story.append(_hr(styles))

    # Dataset overview paragraph
    rows = ov.get("rows", 0)
    cols = ov.get("columns", 0)
    num  = ov.get("numeric_cols", 0)
    cat  = ov.get("categorical_cols", 0)
    miss = ov.get("missing_pct", 0)
    dups = ov.get("duplicate_rows", 0)

    summary_txt = (
        f"The dataset contains <b>{rows:,} rows</b> and <b>{cols} columns</b>, "
        f"comprising {num} numeric and {cat} categorical features. "
        f"Missing data accounts for <b>{miss:.1f}%</b> of all cells"
        + (f", with {dups} duplicate rows detected." if dups else ".")
    )
    story.append(Paragraph(summary_txt, S["body_dark"]))
    story.append(Spacer(1, 0.4*cm))

    # Stats summary cards (table layout)
    num_cols_list = list(analysis.get("numeric", {}).keys())
    if num_cols_list:
        quick_stats = []
        for col in num_cols_list[:6]:
            d = analysis["numeric"][col]
            quick_stats.append([
                col,
                _fmt(d["mean"]), _fmt(d["median"]),
                _fmt(d["std"]),  _fmt(d["min"]),    _fmt(d["max"]),
                f"{d['outlier_pct']:.1f}%",
            ])
        header = ["Column","Mean","Median","Std Dev","Min","Max","Outliers"]
        cw = [4*cm, 2.2*cm, 2.2*cm, 2.2*cm, 2*cm, 2*cm, 1.8*cm]
        story.append(Paragraph("Quick Numeric Summary", S["sub_heading"]))
        story.append(_stats_table([header] + quick_stats, cw))
        story.append(Spacer(1, 0.5*cm))

    # Insights
    if ins:
        story.append(Paragraph("💡 Key Insights", S["sub_heading"]))
        for title, body in ins:
            row_data = [[
                Paragraph(f"<b>{title}</b>", S["insight_title"]),
                Paragraph(body, S["insight_body"]),
            ]]
            t = Table(row_data, colWidths=[5*cm, W - 2*MARGIN - 5*cm])
            t.setStyle(TableStyle([
                ("BACKGROUND",    (0,0), (-1,-1), C_PANEL),
                ("TOPPADDING",    (0,0), (-1,-1), 8),
                ("BOTTOMPADDING", (0,0), (-1,-1), 8),
                ("LEFTPADDING",   (0,0), (-1,-1), 10),
                ("RIGHTPADDING",  (0,0), (-1,-1), 10),
                ("GRID",          (0,0), (-1,-1), 0, colors.transparent),
                ("LINEBELOW",     (0,0), (-1,-1), 1, C_BORDER),
                ("LINEBEFORE",    (0,0), (0,-1),  3, C_AMBER),
            ]))
            story.append(t)
        story.append(Spacer(1, 0.4*cm))

    story.append(PageBreak())


def _numeric_page(story, styles, analysis, charts):
    S   = styles
    num = analysis.get("numeric", {})
    if not num:
        return

    story.append(Paragraph("Numeric Analysis", S["section_heading"]))
    story.append(_hr(styles))

    # Full stats table
    header = ["Column","Count","Mean","Median","Std","Min","Max","Skew","Kurt","Outliers"]
    cw = [3.2*cm,1.6*cm,2*cm,2*cm,2*cm,1.8*cm,1.8*cm,1.6*cm,1.6*cm,1.8*cm]
    rows_data = [header]
    for col, d in num.items():
        rows_data.append([
            col, _fmt(d["count"]), _fmt(d["mean"]), _fmt(d["median"]),
            _fmt(d["std"]),  _fmt(d["min"]),  _fmt(d["max"]),
            _fmt(d["skewness"]), _fmt(d["kurtosis"]),
            f"{d['outlier_pct']:.1f}%",
        ])
    story.append(_stats_table(rows_data, cw))
    story.append(Spacer(1, 0.5*cm))

    # Boxplot
    if "boxplot" in charts:
        story.append(Paragraph("Distribution Overview — Box Plot", S["sub_heading"]))
        img = _img_from_bytes(charts["boxplot"], width=W - 2*MARGIN)
        story.append(img)
        story.append(Paragraph("Boxes show IQR (Q1–Q3). Whiskers extend to 1.5×IQR. Circles are outliers.", S["caption"]))
        story.append(Spacer(1, 0.4*cm))

    # Histograms — 2 per row
    hist_keys = [k for k in charts if k.startswith("hist_")]
    for i in range(0, len(hist_keys), 2):
        row_imgs = []
        for key in hist_keys[i:i+2]:
            img = _img_from_bytes(charts[key], width=(W - 2*MARGIN - 0.4*cm) / 2)
            row_imgs.append(img)
        if len(row_imgs) == 2:
            t = Table([[row_imgs[0], row_imgs[1]]],
                      colWidths=[(W - 2*MARGIN)/2]*2)
            t.setStyle(TableStyle([("LEFTPADDING",(0,0),(-1,-1),0),
                                   ("RIGHTPADDING",(0,0),(-1,-1),4)]))
            story.append(t)
        else:
            story.append(row_imgs[0])
        story.append(Spacer(1, 0.2*cm))

    story.append(PageBreak())


def _categorical_page(story, styles, analysis, charts):
    S   = styles
    cat = analysis.get("categorical", {})
    if not cat:
        return

    story.append(Paragraph("Categorical Analysis", S["section_heading"]))
    story.append(_hr(styles))

    header = ["Column","Count","Unique Values","Top Value","Top Freq","Top %"]
    cw = [4*cm, 2.2*cm, 3*cm, 4.5*cm, 2.5*cm, 2*cm]
    rows_data = [header]
    for col, d in cat.items():
        rows_data.append([
            col, _fmt(d["count"]), _fmt(d["unique"]),
            str(d["top_value"])[:30],
            _fmt(d["top_freq"]), f"{d['top_pct']:.1f}%",
        ])
    story.append(_stats_table(rows_data, cw))
    story.append(Spacer(1, 0.5*cm))

    # Bar + Pie charts
    for col in list(cat.keys())[:2]:
        bar_key = f"bar_{col}"
        pie_key = f"pie_{col}"
        story.append(Paragraph(f"Column: {col}", S["sub_heading"]))
        row_imgs = []
        if bar_key in charts:
            row_imgs.append(_img_from_bytes(charts[bar_key], width=(W - 2*MARGIN - 0.4*cm)/2))
        if pie_key in charts:
            row_imgs.append(_img_from_bytes(charts[pie_key], width=(W - 2*MARGIN - 0.4*cm)/2))
        if len(row_imgs) == 2:
            t = Table([row_imgs], colWidths=[(W - 2*MARGIN)/2]*2)
            t.setStyle(TableStyle([("LEFTPADDING",(0,0),(-1,-1),0),
                                   ("RIGHTPADDING",(0,0),(-1,-1),4)]))
            story.append(t)
        elif row_imgs:
            story.append(row_imgs[0])
        story.append(Spacer(1, 0.4*cm))

    story.append(PageBreak())


def _correlation_page(story, styles, analysis, charts):
    S   = styles
    cor = analysis.get("correlations", {})
    if not cor:
        return

    story.append(Paragraph("Correlation Analysis", S["section_heading"]))
    story.append(_hr(styles))

    # Top pairs table
    pairs = cor.get("top_pairs", [])
    if pairs:
        story.append(Paragraph("Strongest Correlations", S["sub_heading"]))
        header = ["Column A", "Column B", "Pearson r", "Strength"]
        cw_p = [5*cm, 5*cm, 3*cm, 5*cm]
        rows_data = [header]
        for p in pairs[:8]:
            r = p["r"]
            if abs(r) >= 0.8:   strength = "Very Strong"
            elif abs(r) >= 0.6: strength = "Strong"
            elif abs(r) >= 0.4: strength = "Moderate"
            elif abs(r) >= 0.2: strength = "Weak"
            else:               strength = "Very Weak"
            dir_ = "Positive" if r > 0 else "Negative"
            rows_data.append([p["col1"], p["col2"], f"{r:.4f}", f"{dir_} · {strength}"])
        story.append(_stats_table(rows_data, cw_p))
        story.append(Spacer(1, 0.4*cm))

    # Heatmap
    if "corr_heatmap" in charts:
        story.append(Paragraph("Correlation Heatmap", S["sub_heading"]))
        img = _img_from_bytes(charts["corr_heatmap"], width=W - 2*MARGIN)
        story.append(img)
        story.append(Paragraph("Values range from −1 (perfect negative) to +1 (perfect positive).", S["caption"]))
        story.append(Spacer(1, 0.4*cm))

    # Scatter top pair
    if "scatter_top" in charts and pairs:
        p = pairs[0]
        story.append(Paragraph(f"Scatter: '{p['col1']}' vs '{p['col2']}'  (r = {p['r']:.4f})", S["sub_heading"]))
        img = _img_from_bytes(charts["scatter_top"], width=W - 2*MARGIN)
        story.append(img)
        story.append(Spacer(1, 0.4*cm))

    story.append(PageBreak())


def _quality_page(story, styles, analysis, charts):
    S   = styles
    mis = analysis.get("missing", {})
    ov  = analysis.get("overview", {})

    story.append(Paragraph("Data Quality Report", S["section_heading"]))
    story.append(_hr(styles))

    # Summary
    total_miss = ov.get("missing_cells", 0)
    miss_pct   = ov.get("missing_pct", 0)
    dups       = ov.get("duplicate_rows", 0)
    mem        = ov.get("memory_kb", 0)

    kv = [
        ["Total Missing Cells", _fmt(total_miss),     "Missing %",      f"{miss_pct:.2f}%"],
        ["Duplicate Rows",       _fmt(dups),           "Memory (KB)",    _fmt(mem)],
    ]
    kv_data = []
    for row in kv:
        kv_data.append([
            Paragraph(row[0], S["kv_key"]), Paragraph(row[1], S["kv_val"]),
            Paragraph(row[2], S["kv_key"]), Paragraph(row[3], S["kv_val"]),
        ])
    kt = Table(kv_data, colWidths=[(W - 2*MARGIN)/4]*4)
    kt.setStyle(TableStyle([
        ("BACKGROUND",    (0,0), (-1,-1), C_PANEL),
        ("GRID",          (0,0), (-1,-1), 0.4, C_BORDER),
        ("TOPPADDING",    (0,0), (-1,-1), 8),
        ("BOTTOMPADDING", (0,0), (-1,-1), 8),
        ("LEFTPADDING",   (0,0), (-1,-1), 8),
        ("LINEABOVE",     (0,0), (-1, 0), 1.5, C_BLUE),
    ]))
    story.append(kt)
    story.append(Spacer(1, 0.5*cm))

    # Per-column missing table
    if mis:
        story.append(Paragraph("Missing Data by Column", S["sub_heading"]))
        header = ["Column", "Missing Count", "Missing %", "Severity"]
        cw_m   = [6*cm, 3.5*cm, 3*cm, 5.7*cm]
        rows_data = [header]
        for col, d in sorted(mis.items(), key=lambda x: -x[1]["pct"]):
            pct = d["pct"]
            severity = "Critical (>50%)" if pct > 50 else \
                       "High (20–50%)" if pct > 20 else \
                       "Moderate (5–20%)" if pct > 5 else "Low (<5%)"
            rows_data.append([col, _fmt(d["count"]), f"{pct:.2f}%", severity])
        story.append(_stats_table(rows_data, cw_m))
        story.append(Spacer(1, 0.4*cm))

    # Missing heatmap
    if "missing" in charts:
        story.append(Paragraph("Missing Data Map", S["sub_heading"]))
        img = _img_from_bytes(charts["missing"], width=W - 2*MARGIN)
        story.append(img)
        story.append(Paragraph("Red cells indicate missing values across rows and columns.", S["caption"]))
    else:
        story.append(Paragraph("No missing values detected in this dataset.", S["body_dark"]))

    story.append(PageBreak())


def _text_page(story, styles, analysis, charts):
    S    = styles
    txt  = analysis.get("text_stats", {})
    if not txt:
        return

    story.append(Paragraph("Text Analysis", S["section_heading"]))
    story.append(_hr(styles))

    kv = [
        ["Total Characters", _fmt(txt.get("char_count")),   "Word Count",    _fmt(txt.get("word_count"))],
        ["Unique Words",     _fmt(txt.get("unique_words")),  "Sentences",     _fmt(txt.get("sentence_count"))],
        ["Avg Word Length",  _fmt(txt.get("avg_word_length")),"Avg Sent Len", _fmt(txt.get("avg_sentence_length"))],
        ["Lexical Diversity",f"{txt.get('lexical_diversity',0):.4f}", "Lines", _fmt(txt.get("line_count"))],
    ]
    kv_data = []
    for row in kv:
        kv_data.append([
            Paragraph(str(row[0]), S["kv_key"]), Paragraph(str(row[1]), S["kv_val"]),
            Paragraph(str(row[2]), S["kv_key"]), Paragraph(str(row[3]), S["kv_val"]),
        ])
    kt = Table(kv_data, colWidths=[(W - 2*MARGIN)/4]*4)
    kt.setStyle(TableStyle([
        ("BACKGROUND",    (0,0), (-1,-1), C_PANEL),
        ("GRID",          (0,0), (-1,-1), 0.4, C_BORDER),
        ("TOPPADDING",    (0,0), (-1,-1), 8),
        ("BOTTOMPADDING", (0,0), (-1,-1), 8),
        ("LEFTPADDING",   (0,0), (-1,-1), 8),
        ("LINEABOVE",     (0,0), (-1, 0), 1.5, C_BLUE),
    ]))
    story.append(kt)
    story.append(Spacer(1, 0.5*cm))

    if "word_freq" in charts:
        story.append(Paragraph("Top 15 Word Frequencies", S["sub_heading"]))
        img = _img_from_bytes(charts["word_freq"], width=W - 2*MARGIN)
        story.append(img)

    story.append(PageBreak())


def _appendix_page(story, styles, analysis):
    S  = styles
    ov = analysis.get("overview", {})
    fi = analysis.get("file", {})

    story.append(Paragraph("Appendix — Column Inventory", S["section_heading"]))
    story.append(_hr(styles))

    df_obj = fi.get("df")
    num    = analysis.get("numeric", {})
    cat    = analysis.get("categorical", {})
    cols   = ov.get("col_names", [])

    header = ["#", "Column Name", "Data Type", "Category", "Non-Null", "Unique"]
    cw_a   = [1*cm, 5*cm, 3*cm, 3.5*cm, 2.5*cm, 2.5*cm]
    rows_data = [header]
    for i, col in enumerate(cols, 1):
        if df_obj is not None and col in df_obj.columns:
            dtype   = str(df_obj[col].dtype)
            nn      = int(df_obj[col].count())
            uniq    = int(df_obj[col].nunique())
        else:
            dtype = "—"; nn = "—"; uniq = "—"
        cat_label = "Numeric" if col in num else "Categorical" if col in cat else "Other"
        rows_data.append([str(i), col[:35], dtype, cat_label, _fmt(nn), _fmt(uniq)])
    story.append(_stats_table(rows_data, cw_a))


# ─────────────────────────────────────────────────────────────────────────────
# MAIN BUILD FUNCTION
# ─────────────────────────────────────────────────────────────────────────────

def build_report(analysis: dict, charts: dict, output_path: str) -> str:
  
    # Convert to absolute path
    output_path = os.path.abspath(output_path)
    
    # Close any existing file handles and remove old file
    for attempt in range(3):
        if os.path.exists(output_path):
            try:
                os.remove(output_path)
                break
            except PermissionError:
                if attempt < 2:
                    time.sleep(0.5)
                else:
                    # Use temp file and rename approach
                    pass
    
    # Use temp file to avoid permission issues
    temp_dir = tempfile.gettempdir()
    temp_pdf = os.path.join(temp_dir, f"report_temp_{int(time.time() * 1000)}.pdf")
    
    styles = _make_styles()
    story  = []

    fi       = analysis.get("file", {})
    fname    = fi.get("filename", "report")

    def canvas_factory(filename, **kwargs):
        return ReportCanvas(filename, title=fname, filename_short=fname[:40], **kwargs)

    doc = SimpleDocTemplate(
        temp_pdf,
        pagesize=A4,
        leftMargin=MARGIN, rightMargin=MARGIN,
        topMargin=MARGIN + 0.6*cm, bottomMargin=MARGIN + 0.4*cm,
        title=f"Analysis Report — {fname}",
        author="AutoReport · CODTECH Task 2",
    )

    has_df   = fi.get("df") is not None and not fi.get("df", None).empty if fi.get("df") is not None else False
    has_text = bool(analysis.get("text_stats"))

    _cover_page(story, styles, analysis)
    _summary_page(story, styles, analysis)

    if has_df:
        if analysis.get("numeric"):
            _numeric_page(story, styles, analysis, charts)
        if analysis.get("categorical"):
            _categorical_page(story, styles, analysis, charts)
        if analysis.get("correlations"):
            _correlation_page(story, styles, analysis, charts)
        _quality_page(story, styles, analysis, charts)

    if has_text:
        _text_page(story, styles, analysis, charts)

    _appendix_page(story, styles, analysis)

    doc.build(story, canvasmaker=canvas_factory)
    
    # Force garbage collection to release any file handles
    gc.collect()
    time.sleep(0.2)
    
    # Handle file moving with intelligent fallback strategy
    def save_to_output(src_file, dst_file, max_retries=5):
        """Save file with retry logic for locked files."""
        
        # First, try to remove destination if it exists
        for attempt in range(max_retries):
            try:
                if os.path.exists(dst_file):
                    try:
                        os.remove(dst_file)
                    except PermissionError:
                        # If we can't delete, try renaming the old file to a backup
                        backup_file = f"{dst_file}.backup"
                        try:
                            if os.path.exists(backup_file):
                                os.remove(backup_file)
                            os.rename(dst_file, backup_file)
                        except:
                            pass
                
                # Now try to move the temp file
                shutil.move(src_file, dst_file)
                return True
            except (PermissionError, OSError) as e:
                if attempt < max_retries - 1:
                    gc.collect()
                    time.sleep(0.3 * (attempt + 1))
                else:
                    # Final attempt: write directly
                    try:
                        with open(src_file, 'rb') as src:
                            with open(dst_file, 'wb') as dst:
                                dst.write(src.read())
                        try:
                            os.remove(src_file)
                        except:
                            pass
                        return True
                    except Exception as copy_err:
                        raise Exception(f"Failed to save PDF after {max_retries} attempts: {e}, Final error: {copy_err}")
        
        return False
    
    save_to_output(temp_pdf, output_path)
    return output_path
